configuration:  
  projectName: server
soa:
    context:  
      product: /product-api
      loan-management: /loan-management-api
mule:
    context:  
      product: ${soa.context.product}/product-api
      loan-management: ${soa.context.product}/loan-management-api
--- 
spring:  
  profiles: dev
soa:
    context:  
      product: ${soa.context.product}/product-api
      loan-management: ${soa.context.product}/loan-management-api
mule:
    context:  
      product: ${soa.context.product}/product-api
      loan-management: ${soa.context.product}/loan-management-api
---
spring:  
  profiles: qa
soa:
    context:  
      product: ${soa.context.product}/product-api
      loan-management: ${soa.context.product}/loan-management-api
mule:
    context:  
      product: ${soa.context.product}/product-api
      loan-management: ${soa.context.product}/loan-management-api
---
spring:  
  profiles: prd
soa:
    context:  
      product: ${soa.context.product}/product-api
      loan-management: ${soa.context.product}/loan-management-api
mule:
    context:  
      product: ${soa.context.product}/product-api
      loan-management: ${soa.context.product}/loan-management-api