configuration:  
  projectName: server
soa:
  port: 8000
  server: http://dev-soa.qualifacts.com
config:
  user: jsanchez
  pass: '{cipher}24250AQA8SGxnKslAN1xuAPUMTqAbd8oQh7lUlAnY0zZUA7mtozyGUGAgCX3LoaAw5vnmU3ljOcIve8XbM/bydC9YniwBacusAH9HThIw+OIeMxIrHlmoiAqhx3qcwdDTDAlMqCY+wNj4zL9MWtAChTTPe0atsNeh7fY2l8SylPbZlkBOnN/rmdfxgeecGEk27FzqBu78komJd56vSonXEwKfGXKzyUbHTyTpPA8Lxticz0yX09kUZAX9uproeq/vpZ3/AMESOIpnvxixo57q0px/0y9tLTNZBL+z/HZ0WcJlVxyNVMN0jmdLMI0crNNNaqQZ2XwBKD0XnHRpssYKkiyiId0AJ54GbfTdOYcfcpErPs+7Tq9pugt+xTvNzIfXrPTKOB8='
--- 
spring:  
  profiles: dev
soa:  
  port: 80
  server: http://dev-soa.qualifacts.com
mule:
  port: 80
  server: http://dev-mule.qualifacts.com
config:
  user: jsanchez
  pass: '{cipher}24250AQA8SGxnKslAN1xuAPUMTqAbd8oQh7lUlAnY0zZUA7mtozyGUGAgCX3LoaAw5vnmU3ljOcIve8XbM/bydC9YniwBacusAH9HThIw+OIeMxIrHlmoiAqhx3qcwdDTDAlMqCY+wNj4zL9MWtAChTTPe0atsNeh7fY2l8SylPbZlkBOnN/rmdfxgeecGEk27FzqBu78komJd56vSonXEwKfGXKzyUbHTyTpPA8Lxticz0yX09kUZAX9uproeq/vpZ3/AMESOIpnvxixo57q0px/0y9tLTNZBL+z/HZ0WcJlVxyNVMN0jmdLMI0crNNNaqQZ2XwBKD0XnHRpssYKkiyiId0AJ54GbfTdOYcfcpErPs+7Tq9pugt+xTvNzIfXrPTKOB8='
---
spring:  
  profiles: qa
soa:  
  port: 80
  server: http://qa-soa.qualifacts.com
mule:
  port: 80
  server: http://qa-mule.qualifacts.com
config:
  user: jsanchez
  pass: '{cipher}24250AQA8SGxnKslAN1xuAPUMTqAbd8oQh7lUlAnY0zZUA7mtozyGUGAgCX3LoaAw5vnmU3ljOcIve8XbM/bydC9YniwBacusAH9HThIw+OIeMxIrHlmoiAqhx3qcwdDTDAlMqCY+wNj4zL9MWtAChTTPe0atsNeh7fY2l8SylPbZlkBOnN/rmdfxgeecGEk27FzqBu78komJd56vSonXEwKfGXKzyUbHTyTpPA8Lxticz0yX09kUZAX9uproeq/vpZ3/AMESOIpnvxixo57q0px/0y9tLTNZBL+z/HZ0WcJlVxyNVMN0jmdLMI0crNNNaqQZ2XwBKD0XnHRpssYKkiyiId0AJ54GbfTdOYcfcpErPs+7Tq9pugt+xTvNzIfXrPTKOB8='
---
spring:  
  profiles: prd
soa:  
  port: 80
  server: http://prd-soa.qualifacts.com
mule:
  port: 80
  server: http://prd-mule.qualifacts.com
config:
  user: jsanchez
  pass: '{cipher}24250AQA8SGxnKslAN1xuAPUMTqAbd8oQh7lUlAnY0zZUA7mtozyGUGAgCX3LoaAw5vnmU3ljOcIve8XbM/bydC9YniwBacusAH9HThIw+OIeMxIrHlmoiAqhx3qcwdDTDAlMqCY+wNj4zL9MWtAChTTPe0atsNeh7fY2l8SylPbZlkBOnN/rmdfxgeecGEk27FzqBu78komJd56vSonXEwKfGXKzyUbHTyTpPA8Lxticz0yX09kUZAX9uproeq/vpZ3/AMESOIpnvxixo57q0px/0y9tLTNZBL+z/HZ0WcJlVxyNVMN0jmdLMI0crNNNaqQZ2XwBKD0XnHRpssYKkiyiId0AJ54GbfTdOYcfcpErPs+7Tq9pugt+xTvNzIfXrPTKOB8='