configuration:  
  projectName: server
soa:
  port: 8000
  server: http://dev-soa.qualifacts.com
--- 
spring:  
  profiles: dev
soa:  
  port: 80
  server: http://dev-soa.qualifacts.com
mule:
  port: 80
  server: http://dev-mule.qualifacts.com
---
spring:  
  profiles: qa
soa:  
  port: 80
  server: http://qa-soa.qualifacts.com
mule:
  port: 80
  server: http://qa-mule.qualifacts.com
---
spring:  
  profiles: prd
soa:  
  port: 80
  server: http://prd-soa.qualifacts.com
mule:
  port: 80
  server: http://prd-mule.qualifacts.com